### ISSUE TITLE
Implement multiple tag values for each run

### ISSUE THREAD

**Issue by sbpcs59** [NCEAS/recordr#35]
In the viewRuns() design review, it was mentioned by @mbjones that recordr should allow multiple
tag values for each run. Notes currently at https://docs.google.com/document/d/13VmbVyJQJ5-7LxVWV0DI7JhCTPfFRmrCSJiyVJnixD4/edit?pli=1

Should all these tags be specified at the time the script is run?
Should searches (i.e. listRuns()) search all tag fields or should they be searched separately
i.e. tag1="search term 1", tag2="search term2"?

**Comment by mbjones** [comment]
@sbpcs59 I think users should be able to add (and maybe remove) tags from runs after the run has happened.  This lets them impose some order on a large number of runs as they run them.  Searches should search across all tags, and I don't think we should have multiple tag fields -- rather, it should be presented as a single multi-valued field (even though behind the scenes there may be a separate table for tags in the database).

**Comment by sbpcs59** [comment]
The initial version of implementing multiple tags has been added in commit 76eb540794b868d45a5fb82bc6b41402431c8705. This version allows multiple tags
to be added during record() or startRecordr(), i.e.

```
record(rc, file="foo.r", tag=c("one", "two", "three")
```
To be done: allow editing of tags for a run.
