### ISSUE TITLE
Display shortened version of long filenames and run identifiers

### ISSUE THREAD

**Issue by sbpcs59** [NCEAS/recordr#36]
For listRuns() and possibly viewRuns(), display long filenames and run identifiers in a shortened
form, e.g.:
```
    /Users/slaughter/data/codyn/plot10/run1/model12/knz_001d.csv
```

would be shortened to
```
/Users/slaug...knz_001d.csv

Run Identifiers would be shortened from
```
urn:uuid:e6a6c448-ca4b-45ea-8478-de257d3b2843
```

to

```
...2843
````

Functions that search based on a run identifier will allow wildcards to match the
end of the id, i.e. listRuns(rc, id="*2843") and all matching runs will be returned.

**Comment by mbjones** [comment]
@sbpcs59 The git/GitHub model for shortening SHA checksums would be a good guide for how to do this.  A few more than 4 characters may be warranted.  They use 10 characters, like this:

latest commit `f3f5046966`

Ten would likely get some of the substance, whereas 4 might only be something like '.csv'.

**Comment by sbpcs59** [comment]
viewRuns() displays shortened filenames and identifiers, since commit  55889a164e68eb8e955bb33667f925e6d2a6dd5e
