### ISSUE TITLE
entity name missing in metadata for generated tables

### ISSUE THREAD

**Issue by mbjones** [NCEAS/recordr#43]
Input data object name not provided, so identifier is used in display rather than object name as it should have been.

**Comment by lauren-walker** [comment]
(From Commdyn demo on 10/05) - The problem here was that the data table was not being included in the resource map, so it wasn't being displayed in MetacatUI as part of the package, and therefore didn't get linked up with its entity name.

**Comment by sbpcs59** [comment]
The filename of an object is entered as the EML <otherEntity><entityName> value, changed in
commit a9601ba73da676157ca4775a62bc3f957b3e9dbf
