### ISSUE TITLE
Recordr fails to install with a fresh R installation

### ISSUE THREAD

**Issue by amoeba** [NCEAS/recordr#56]
I cleared my lib path of all installed packages and followed the installation steps outlined in the README. Everything went fine until `install.packages("recordr")`, which resulted in (previous output elided)...

```
...
* installing *source* package ‘recordr’ ...
** R
** inst
** preparing package for lazy loading
Note: the specification for class “ExternalReference” in package ‘redland’ seems equivalent to one from package ‘XML’: not turning on duplicate class definitions for this class.
Warning: replacing previous import by ‘httr::handle_reset’ when loading ‘dataone’
Warning: replacing previous import by ‘parsedate::parse_date’ when loading ‘dataone’
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘ggplot2’
ERROR: lazy loading failed for package ‘recordr’
* removing ‘/usr/local/lib/R/3.2/site-library/recordr’
Warning in install.packages :
  installation of package ‘recordr’ had non-zero exit status
```

I solved this by installing ggplot2 manually with `install.packages('ggplot')`. After I did this, recordr installed successfully. I see that ggplot2 is imported in the NAMESPACES file but is not listed as a dependency. Is this what caused the problem?

**Comment by sbpcs59** [comment]
ggplot2, png, dataone packages are properly loaded only if the package is installed (using loadNamespace) since commit bdd9f40e6c9163d6b2d9a7a750491420d33c457b
